dataset-path-train: '/workspaces/rtsptoweb/dataset_action_split/test_yolov7.pkl'
dataset-path-test: '/workspaces/rtsptoweb/dataset_action_split/test_yolov7.pkl'
epochs: 50
project: 'runs'
batch-size: 64
img-size: 64
num-frame: 30

